CREATE TABLE `user` (
                        `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '用户ID',
                        `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户名',
                        `email` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '邮箱',
                        `phone` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '手机号',
                        `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '密码',
                        `avatar_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '头像URL',
                        `gender` tinyint DEFAULT NULL COMMENT '性别: 0-未知, 1-男, 2-女',
                        `birthday` date DEFAULT NULL COMMENT '生日',
                        `bio` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '个人简介',
                        `vip_level` tinyint unsigned DEFAULT '0' COMMENT 'VIP等级: 0-普通，2-VIP会员，3-SVIP会员',
                        `vip_start_at` datetime DEFAULT NULL COMMENT 'VIP开始时间',
                        `vip_expire_at` datetime DEFAULT NULL COMMENT 'VIP到期时间',
                        `account_status` tinyint DEFAULT '1' COMMENT '账户状态: 0-禁用, 1-正常，3-删除',
                        `last_login_at` datetime DEFAULT NULL COMMENT '最后登录时间',
                        `last_login_ip` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '最后登录IP',
                        `last_active_at` datetime DEFAULT NULL COMMENT '最后活跃时间',
                        `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                        `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                        `delete_time` datetime DEFAULT NULL COMMENT '软删除时间',
                        PRIMARY KEY (`id`),
                        UNIQUE KEY `username` (`username`),
                        UNIQUE KEY `email` (`email`),
                        UNIQUE KEY `phone` (`phone`),
                        KEY `idx_email` (`email`),
                        KEY `idx_phone` (`phone`),
                        KEY `idx_username` (`username`),
                        KEY `idx_account_status` (`account_status`),
                        KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户主表';